### ISSUE TITLE
Chapter 2: 'Perceptron' object has no attribute 'errors_'

### ISSUE THREAD

**Issue by felix4webscience** [rasbt/python-machine-learning-book-2nd-edition#102]
Hi,

I know there exists an already closed issue on this topic, which is the reason I have taken the same headline. 
Given the code for the Perceptron algorithm is correct before, I have  the following issue with this block of code

`ppn = Perceptron(eta=0.1, n_iter=10)
ppn.fit(X, y)
plt.plot(range(1, len(ppn.errors_) + 1), ppn.errors_, marker='o')
plt.xlabel('Epochs')
plt.ylabel('Number of updates')`

because it tells me that Perceptron has no attribute "errors"

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-28d20e46880a> in <module>
----> 1 ppn = Perceptron(eta=0.1, n_iter=10)
      2 ppn.fit(X, y)
      3 plt.plot(range(1, len(ppn.errors_) + 1), ppn.errors_, marker='o')
      4 plt.xlabel('Epochs')
      5 plt.ylabel('Number of updates')

TypeError: object() takes no parameters`

I have retyped everything again and again and also tried the solution from this GitHub repository but this error remains the same. And I don't know why. I hope someone can easily help me out?
Greetings
F.

**Comment by rasbt** [comment]
Hi there. You shouldn't execute all the code on one line. In Python (in contrast to certain other programming languages) spacing is important. So you need to execute the commands on separate lines.

Instead of

    ppn = Perceptron(eta=0.1, n_iter=10) ppn.fit(X, y)

you need to do

    ppn = Perceptron(eta=0.1, n_iter=10)
    ppn.fit(X, y)

**Comment by felix4webscience** [comment]
Hi, 
Thank you. Well, somehow this did not work on my mac environment after recoding everything in pycharm in my windows environment it worked. I have no idea why, maybe a spelling error somewhere. 
But anyhow. Thanks a lot.

**Comment by rasbt** [comment]
Yeah, it was probably due to some minor formatting issue or typo. These can sometimes be hard to see, and I am glad that the problem solved itself :).
