### ISSUE TITLE
Chapter 9: update.py

### ISSUE THREAD

**Issue by dongpohezui** [rasbt/python-machine-learning-book-2nd-edition#115]
When I run "/code/ch09/movieclassifier_with_update/update.py ",something is wrong.

After I deleted this line "from update import update_model", things seemed right.

What dose the line "from update import update_model" mean? Is it redundant?

Thanks!

**Comment by rasbt** [comment]
Thanks for the note. You are right, this line is redundant. I just double-checked with the PDF, and there it seems to be correct. The line 

    # import update function from local dir
    from update import update_model

is redundant and should be removed like you pointed out. Just fixed it in the repo. Thanks
