### ISSUE TITLE
Web Application Not starting after running app.py in terminal

### ISSUE THREAD

**Issue by datatales2017** [rasbt/python-machine-learning-book-2nd-edition#45]
The complete code is displayed in a notepad after executing the commands.
This is my folder structure:
flaskapp1/
	app.py
	templates/
		first_app.html
Below are the commands I ran in terminal:
S:\>cd flaskapp1
S:\flaskapp1>app.py
[error.docx](https://github.com/rasbt/python-machine-learning-book-2nd-edition/files/1420062/error.docx)
[error.docx](https://github.com/rasbt/python-machine-learning-book-2nd-edition/files/1420064/error.docx)

OS: windows10

**Comment by rasbt** [comment]
Hi there,

the error message is a bit confusing, because docx is a Microsoft Word format, right? Can you try to execute "app.py" via

    python3 app.py

(or just `python app.py` depending on your system setup) to see if that solves the issue?

**Comment by datatales2017** [comment]
python3 app.py gives an error.
I used python ./app.py and it worked
