### ISSUE TITLE
Small error in code

### ISSUE THREAD

**Issue by wmvanvliet** [rasbt/python-machine-learning-book-2nd-edition#46]
on this line:

https://github.com/rasbt/python-machine-learning-book-2nd-edition/blob/063b6734b5f857b18b1790e95526445ac62111af/code/ch12/neuralnet.py#L58

`y.shape[0]` is already a plain integer.

**Comment by rasbt** [comment]
Thanks for the note, just removed the extra int casting. Kind of weird, it only appeared in the neuralnet.py code, seems like I already removed that some time ago in the actual book code in ch12.py / ch12.ipynb

Anyways, thanks!
