### ISSUE TITLE
p(i|t) is proportion in class i

### ISSUE THREAD

**Issue by geier** [rasbt/python-machine-learning-book-2nd-edition#50]
I believe I found a small issue with the nomenclature in chapter 3, section "Maximizing information gain – getting the most bang for your buck" on page 91 of the packt pdf.

It currently reads:
> Here, p (i | t ) is the proportion of the samples that belong to class c for a particular node t.

I believe that should be:
> Here, p (i | t ) is the proportion of the samples that belong to class *i* for a particular node t.

(i instead of c).

**Comment by rasbt** [comment]
You are right, good catch, will add that to the errata! Thanks
