### ISSUE TITLE
Chapter 7, ensemble learning

### ISSUE THREAD

**Issue by gabramson** [rasbt/python-machine-learning-book-2nd-edition#56]
On pdf page 248 (labeled 221 on the page), there are two equations at the bottom of the page:
![image](https://user-images.githubusercontent.com/31111688/34623547-6ac98512-f217-11e7-9878-5ee2432a906e.png)

The complement of the error should be (1 - epsilon) in the first equation and (1 - 0.25) in the second. They are reversed.

**Comment by rasbt** [comment]
Thanks so much for the note! Yes, this is indeed a mix up. In the first edition, it had the "epsilon" in the correct edition, but it also had the epsilon in the lower one and asked the layout team to fix it. They must have applied the fix to the wrong equation :(. Will add that to the errata!
