### ISSUE TITLE
Chapter 2: 'Perceptron' object has no attribute 'errors_'

### ISSUE THREAD

**Issue by SumoBBQ** [rasbt/python-machine-learning-book-2nd-edition#57]
Hi, 
I found your book very useful for a newbie like me and I am trying to recode all your codes...
In the following lines of code:
```
ppn = Perceptron(eta=0.1, n_iter=10)
ppn.fit(X, y)
plt.plot(range(1, len(ppn.errors_) + 1), ppn.errors_, marker='o')
plt.xlabel('Epochs')
plt.ylabel('Number of updates')

```
I see that, you use `len(pnn.errors_)` and there is no problem. But when i try this:
```
ppn = Perceptron(eta=0.1, n_iter=10)
print(len(ppn.errors_))
ppn.fit(X, y)
plt.plot(range(1, len(ppn.errors_) + 1), ppn.errors_, marker='o')
plt.xlabel('Epochs')
plt.ylabel('Number of updates')
```
I run into this error: **'Perceptron' object has no attribute 'errors_'**. I know something is wrong with 
`print(len(ppn.errors_))` but i don't know why. Can you explained in more detail? Thank you in advance.

**Comment by rasbt** [comment]
Hey, there,

sorry about the confusion, but the `errors_` attribute does not exist prior to calling `fit`. There's a small paragraph about that on pg. 24:

> We will take an object-oriented approach to define the perceptron interface as a Python class, which allows us to initialize new Perceptron objects that can learn from data via a `fit` method, and make predictions via a separate predict method. As a convention, we append an underscore (`_`) to attributes that are not being created upon the initialization of the object but by calling the object's other methods, for example, `self.w_`.

But yeah, that's easy to overlook :). Basically, that's being done to be consistent with scikit-learn, which is introduced in the next chapter.

Hope that clarifies (and addresses) the issue! :)
