### ISSUE TITLE
Chapter 11 issues

### ISSUE THREAD

**Issue by gabramson** [rasbt/python-machine-learning-book-2nd-edition#59]
- The image on page 366 is supposed to be the pair-wise distance square matrix, but instead it is a repeat of the sample data image from page 365.

- Page 368, 1st paragraph, the text reads:

> The first and second columns denote the most 
dissimilar members in each cluster, and the third _row_ reports the distance between 
those members.

It should say "third column"

- Page 371, last paragraph, the text reads:

> As we can see, in this pruned clustering hierarchy, label ID_3 was _not_ assigned to the 
same cluster as ID_0 and ID_4, as expected.

It should say "label ID_3 was assigned"

Sincerely,
Gary

**Comment by rasbt** [comment]
Thanks for the feedback, and sorry about the trouble. You are correct on all three accounts, and I added these issues to the errata
