### ISSUE TITLE
Minor typo?

### ISSUE THREAD

**Issue by olivertomic** [rasbt/python-machine-learning-book-2nd-edition#63]
There might be a minor typo on page 88. The very last sentence says "... by making decision based on asking ...". I would guess it was supposed to say "... by making decision**s** based on ... "? Alternatively "... by making **a** decision based on ..."?

**Comment by rasbt** [comment]
Thanks! Yeah, there's definitely some weird grammar in that sentence, and I think I meant to say "making **a** decision" (but "making decision**s**") would be also fine. Will add that to the things-to-be-fixed-in-a-reprint list!
