### ISSUE TITLE
Wrong reference in code?

### ISSUE THREAD

**Issue by olivertomic** [rasbt/python-machine-learning-book-2nd-edition#66]
My apologies if I have completely misunderstood this. Regarding feature selection using Random Forest the code on page 138 says :

print('Number of samples that meet this criterion:', 
         X_selected.shape[0])

I would have expected rather this line of code:

print('Number of features that meet this criterion:', 
      X_selected.shape[1])

since we are discussing feature selection and we set the threshold criterion for features importances.

**Comment by rasbt** [comment]
Hi, Oliver,

thanks for the note! Not sure what I was trying to do there, and your suggestion is much more sensical and I changed it in the code
