### ISSUE TITLE
minor typos

### ISSUE THREAD

**Issue by jblocher** [rasbt/python-machine-learning-book-2nd-edition#71]
On page 101, you say the RandomForestClassifier uses the entropy criterion, but the code clearly says criterion='gini' both in the text and the downloaded code. 

Excellent book, by the way.

**Comment by jblocher** [comment]
Another tiny typo: in the ch06.ipynb, the alternate local reading of the Wisconsin data names the dataframe `df_wine` instead of `df` which I assume is a copy/paste error from the previous chapter.

**Comment by rasbt** [comment]
Thanks a lot, should be all addressed now!
