### ISSUE TITLE
Typo at location 1395

### ISSUE THREAD

**Issue by brisingr002** [rasbt/python-machine-learning-book-2nd-edition#73]
In chapter 3 - Number of misclassified samples with sklear perceptron, there is a small typo in the equation 6/45 = 0.067 -> should be 3/45 (3 misclassified samples).

The book is otherwise excellent!

**Comment by rasbt** [comment]
Thanks, that should already be addressed in the recent reprint. Along with some other typos (mainly those listed in the errata. I think the reprint came out a few weeks ago, but I will double check with the publisher. Thanks for letting me know!
