### ISSUE TITLE
Chapter 2 - typo at page 28

### ISSUE THREAD

**Issue by cciprianmihai** [rasbt/python-machine-learning-book-2nd-edition#96]
Hello, 

I have discovered a little typo at the beginning of the notes section of page 28, Chapter 2. 

"Instead of using NumPy to calculate the vector dot product between two arrays `a` and `b` via `a.dot(b)` or `np.dot(a, b)`, we could also perform the calculation in pure Python via `sum([j * j for i, j in zip(a, b)])`". I think that it should be `sum([i * j for i, j in zip(a, b)])`.

Thank you!

**Comment by rasbt** [comment]
Thanks a lot. I am currently preparing the 3rd edition and appreciate that! I was just checking the PDF though and it appears to be correct there. When I remember correctly, this was fixed early ~2018; Packt had temporarily a version online where this issue occurred. Thanks for noting though!
